# 生产环境配置 prod
spring:

  # 项目名称
  application:
    name: user-center

  # 配置数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://remote/link_partner?characterEncoding=utf-8&useSSL=false
    username: root
    password: xxxxxx

  # 配置redis
  redis:
    # Redis服务器地址
    host: remote
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 20000
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool.max-active: 20
      # 最大阻塞等待时间(负数表示没限制)
      pool.max-wait: -1
      # 连接池中的最大空闲连接
      pool.max-idle: 5
      # 连接池中的最小空闲连接
      pool.min-idle: 0

server:
  port: 8443
  # 指定接口全局路径前缀
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 项目域名
#        same-site: lax
#        secure: false
