# 生产环境配置 prod
spring:

  # 配置数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/link_partner?characterEncoding=utf-8&useSSL=false
    username: root
    password: Zc19981211@
